<a href="https://colab.research.google.com/github/jsyoo1229/orm/blob/main/240122_Pandas_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###1.판다스 개요

In [ ]:
import pandas as pd

# 데이터프레임 생성
data = {'이름': ['홍길동', '임꺽정', '이순신'],
        '나이': [30, 20, 40],
        '도시': ['서울', '부산', '광주']}
df = pd.DataFrame(data)
# print(df)
# df.info()
# df.describe()

df.dropna(inplace = True)
df

df.shape
df.dtypes
df.index
df.columns

df.rename(columns={'이름': 'name', '나이': 'age', ' 도시': 'city'})
# df.columns('A', 'B', 'C')
df.drop('age', axis=1)

KeyError: "['age'] not found in axis"

In [ ]:
import pandas as pd

data = {'이름': ['a', 'b', 'c'],
        '나이': [20, 23, 24],
        '도시': ['서울', '뉴욕', '런던']}

df = pd.DataFrame(data)
print(df)

  이름  나이  도시
0  a  20  서울
1  b  23  뉴욕
2  c  24  런던

In [ ]:
names = pd.Series(['서울', '뉴욕', '런던'])

print(names)
type(names)

0    서울
1    뉴욕
2    런던
dtype: object

pandas.core.series.Series

In [ ]:
test = pd.read_csv('/content/sample_data/california_housing_test.csv')
print(test.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0
1    -118.30     34.26                43.0       1510.0           310.0
2    -117.81     33.78                27.0       3589.0           507.0
3    -118.36     33.82                28.0         67.0            15.0
4    -119.67     36.33                19.0       1241.0           244.0

   population  households  median_income  median_house_value
0      1537.0       606.0         6.6085            344700.0
1       809.0       277.0         3.5990            176500.0
2      1484.0       495.0         5.7934            270500.0
3        49.0        11.0         6.1359            330000.0
4       850.0       237.0         2.9375             81700.0
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0
         longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000
mean   -119.589200    35.63539           28.845333   2599.578667
std       1.994936     2.12967           12.555396   2155.593332
min    -124.180000    32.56000            1.000000      6.000000
25%    -121.810000    33.93000           18.000000   1401.000000
50%    -118.485000    34.27000           29.000000   2106.000000
75%    -118.020000    37.69000           37.000000   3129.000000
max    -114.490000    41.92000           52.000000  30450.000000

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000
mean       529.950667   1402.798667   489.91200       3.807272
std        415.654368   1030.543012   365.42271       1.854512
min          2.000000      5.000000     2.00000       0.499900
25%        291.000000    780.000000   273.00000       2.544000
50%        437.000000   1155.000000   409.50000       3.487150
75%        636.000000   1742.750000   597.25000       4.656475
max       5419.000000  11935.000000  4930.00000      15.000100

       median_house_value
count          3000.00000
mean         205846.27500
std          113119.68747
min           22500.00000
25%          121200.00000
50%          177650.00000
75%          263975.00000
max          500001.00000

In [ ]:
test = pd.read_csv('/content/sample_data/california_housing_test.csv')
test.shape
test.dtypes
test.index
test.columns

test[['housing_median_age']]
test.loc[2, 'housing_median_age']
# test.loc[2, 'housing_median_age'] = np.nan
test[['housing_median_age']]
test[['housing_median_age']].isnull()

data = pd.Series(([10, 12, 20, 30]))
data.sum()

72

In [ ]:
pd.to_numeric()

In [ ]:
# Sample DataFrames
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

In [ ]:
df1

   A  B
0  1  3
1  2  4

In [ ]:
df2

   A  B
0  5  7
1  6  8

In [ ]:
# 가로로 연결 (열 방향)
result = pd.concat([df1, df2], axis=1)

print(result)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [ ]:
EPL = pd.read_csv('/content/2021-2022.csv')
EPL
EPL.shape
EPL.dtypes
EPL.index
EPL.columns
EPL
# EPL['FTHG'] = EPL['FTHG'].astype(int)
# EPL.dtypes['FTHG']
EPL['Date'] = pd.to_datetime(EPL['Date'])
EPL.dtypes
EPL['FTHG']

<ipython-input-102-837bd0e43907>:10: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  EPL['Date'] = pd.to_datetime(EPL['Date'])

0      2
1      5
2      1
3      3
4      3
      ..
375    1
376    4
377    3
378    3
379    0
Name: FTHG, Length: 380, dtype: int64

In [ ]:
EPL

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,2021-08-13,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,2021-08-14,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,2021-08-14,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,2021-08-14,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,2021-08-14,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,2022-05-22,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,2022-05-22,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,2022-05-22,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,2022-05-22,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,2022-05-22,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [ ]:
EPL['FTHG'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 380 entries, 0 to 379
Series name: FTHG
Non-Null Count  Dtype
--------------  -----
380 non-null    int64
dtypes: int64(1)
memory usage: 3.1 KB

In [ ]:
EPL[['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   HomeTeam  380 non-null    object
 1   AwayTeam  380 non-null    object
 2   FTHG      380 non-null    int64
 3   FTAG      380 non-null    int64
dtypes: int64(2), object(2)
memory usage: 12.0+ KB

In [ ]:
EPL.loc[2:8, 'AwayTeam']

2          Brighton
3    Crystal Palace
4       Southampton
5            Wolves
6       Aston Villa
7         Liverpool
8          West Ham
Name: AwayTeam, dtype: object

In [ ]:
import numpy as np

EPL.loc[3, 'AwayTeam'] = np.nan
EPL['AwayTeam']

0          Arsenal
1            Leeds
2         Brighton
3              NaN
4      Southampton
          ...
375     Man United
376    Southampton
377         Wolves
378    Aston Villa
379      Tottenham
Name: AwayTeam, Length: 380, dtype: object

In [ ]:
EPL['AwayTeam'].isnull()
EPL.isnull()

In [ ]:
EPL['FTHG'] + 1
EPL['FTHG'] * 2
High_FTHG = EPL['FTHG'] > 2
# High_FTHG.head()
test = EPL['FTHG']
filtered = test[High_FTHG]
filtered.head()
# EPL['FTHG'][EPL['FTHG'] > 2]
# EPL['FTHG']

1     5
3     3
4     3
6     3
14    5
Name: FTHG, dtype: int64

In [ ]:
EPL

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,2021-08-13,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,2021-08-14,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,2021-08-14,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,2021-08-14,15:00,Chelsea,NaN,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,2021-08-14,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,2022-05-22,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,2022-05-22,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,2022-05-22,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,2022-05-22,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,2022-05-22,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [ ]:
EPL2 = EPL.rename(columns = {'HomeTeam': 'Home'})
EPL2

,Div,Date,Time,Home,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,2021-08-13,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,2021-08-14,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,2021-08-14,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,2021-08-14,15:00,Chelsea,NaN,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,2021-08-14,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,2022-05-22,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,2022-05-22,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,2022-05-22,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,2022-05-22,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,2022-05-22,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [ ]:
import pandas as pd

# Sample DataFrames
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

result = pd.concat([df1, df2], axis=1) #axis=1

print(result)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [ ]:
result = pd.concat([df1, df2], axis=0)
print(result)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [ ]:
result = pd.concat([df1, df2])
print(result)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [ ]:
result.drop('A', axis = 1)

   B
0  3
1  4
0  7
1  8

In [ ]:
import pandas as pd

# Sample DataFrames
df1 = pd.DataFrame({'A': [1, None], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, None], 'B': [7, 8]})

result = pd.concat([df1, df2], axis=1) #axis=1
result.dropna()

     A  B    A  B
0  1.0  3  5.0  7
1  NaN  4  NaN  8

     A  B    A  B
0  1.0  3  5.0  7

In [ ]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

In [ ]:
pd.Series([10, 20, 30, 80]).sum()
pd.Series([10, 20, 30, 80]).mean()
pd.Series([10, 20, 30, 80]).value_counts()

10    1
20    1
30    1
80    1
dtype: int64

In [ ]:
EPL.iloc[:, 5]

0      2
1      5
2      1
3      3
4      3
      ..
375    1
376    4
377    3
378    3
379    0
Name: FTHG, Length: 380, dtype: int64

In [ ]:
EPL.isnull().sum()

Div         0
Date        0
Time        0
HomeTeam    0
AwayTeam    1
           ..
PCAHA       0
MaxCAHH     0
MaxCAHA     0
AvgCAHH     0
AvgCAHA     0
Length: 106, dtype: int64

In [ ]:
EPL.nunique()

Div           1
Date        123
Time         14
HomeTeam     20
AwayTeam     20
           ...
PCAHA        53
MaxCAHH      50
MaxCAHA      50
AvgCAHH      42
AvgCAHA      45
Length: 106, dtype: int64

###EDA 실습

In [ ]:
import pandas as pd
dataset = pd.read_csv('/content/The-Big-List-20231127-Reviews-to-4650.csv', encoding='latin1')
dataset

In [ ]:
dataset.head()

In [ ]:
dataset.describe()

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4650 entries, 0 to 4649
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  4650 non-null   int64
 1   Brand     4650 non-null   object
 2   Variety   4650 non-null   object
 3   Style     4650 non-null   object
 4   Country   4650 non-null   object
 5   Stars     4648 non-null   object
 6   T         0 non-null      float64
dtypes: float64(1), int64(1), object(5)
memory usage: 254.4+ KB

In [ ]:
dataset['Brand'].value_counts()

Nissin             567
Maruchan           182
Myojo              152
Nongshim           136
Samyang Foods      122
                  ...
Kiseki Foods         1
Xiuhe                1
Dr. McDougall's      1
Hi-Lai Foods         1
Westbrae             1
Name: Brand, Length: 698, dtype: int64

In [ ]:
dataset.nunique()

Review #    4650
Brand        698
Variety     4325
Style         10
Country       54
Stars         53
T              0
dtype: int64

In [ ]:
dataset.isnull().sum()

Review #       0
Brand          0
Variety        0
Style          0
Country        0
Stars          2
T           4650
dtype: int64

In [ ]:
dataset = dataset.drop('T', axis = 1)

In [ ]:
dataset.info()

In [ ]:
# Rank : Rank of the player
# Player : Player name
# Team : Player team name
# GP : Games played
# GS : Games started
# MIN : Minutes played
# G : Goals
# ASST : Assists
# SHOTS : Total shots
# SOG : Shots on goal

In [9]:
import pandas as pd
EPL_Player = pd.read_csv('/content/Premier League Player Stats.csv')

sorted_EPL_Player = EPL_Player.sort_values(by='ASST', ascending=False).head(20)
sorted_EPL_Player.reset_index(drop=True, inplace=True)
sorted_EPL_Player.index += 1
top_20 = sorted_EPL_Player.head(20)
sorted_EPL_Player[['TEAM','PLAYER', 'ASST']]
# EPL_Player

                       TEAM                                   PLAYER  ASST
1           Manchester City                          Kevin De Bruyne    20
2                 Liverpool                   Trent Alexander-Arnold    13
3                 Liverpool                         Andrew Robertson    12
4           Manchester City                              David Silva    10
5                 Liverpool                      Mohamed Salah Ghaly    10
6         Tottenham Hotspur                            Heung-Min Son    10
7   Wolverhampton Wanderers                             Adama Traoré     9
8           Manchester City                             Riyad Mahrez     9
9                 Liverpool      Roberto Firmino Barbosa de Oliveira     8
10           Leicester City                            Harvey Barnes     8
11        Manchester United                          Marcus Rashford     7
12        Manchester United            Bruno Miguel Borges Fernandes     7
13                Liverpool                               Sadio Mané     7
14                  Everton                              Lucas Digne     7
15          Manchester City  Bernardo Mota Veiga de Carvalho e Silva     7
16             Norwich City                         Emiliano Buendía     7
17          Manchester City                Gabriel Fernando de Jesus     7
18                  Chelsea                  Willian Borges Da Silva     7
19        Manchester United                             Daniel James     6
20           Leicester City                          Youri Tielemans     6

In [2]:
Goal_Rank = EPL_Player.sort_values(by='G', ascending = False).head(20)
Goal_Rank[['PLAYER', 'Team','G']]

NameError: name 'EPL_Player' is not defined